name:  ScrollerBar
author:  arieh
current:  0.5.4
category:  Interface
tags:  [scroller,scrollbar, costum scrollbar]
demo:  http://arieh.github.com/ScrollBar
docs:  http://moodocs.net/arieh/ScrollBar/scrollbar
